---
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R tutorials

This is a list of tutorials that are being developed for first year stats at Lancaster. They use the `learnr` package and are hosted on a shiny server. This means they provide interactive tutorials, with feedback and solutions. They do not require the user to work within R Studio, unless specified in the tutorial (there are some exercises to develop familiarity with R Studio). 

This list will grow as we develop the tutorials. What is posted here is in a reasonably complete state, but there may be bugs/typos etc. Any feedback and suggestions are welcome - please email t.beesley@lancaster.ac.uk

### [Intro](https://tombeesley.shinyapps.io/1_intro_to_R_learnr)

This is a basic example of a learnr tutorial, mainly for demo purposes, but might form the basis of some of our exercises in the early weeks of the course.


### [Week 6](https://tombeesley.shinyapps.io/Week_6/)

This is a more complete set of exercises, focusing first on development of programming skills, with verbs `select()`, `filter()`, and use of `%>%`. It then explores the concepts of sampling data and the effect that has on resulting distributions of data observed.


